export const ACTION = {
  INIT: 'INIT',
  MOVE_NORTH: 'MOVE_NORTH',
  MOVE_SOUTH: 'MOVE_SOUTH',
  MOVE_EAST: 'MOVE_EAST',
  MOVE_WEST: 'MOVE_WEST',
  CONFIRM: 'CONFIRM',
  CANCEL: 'CANCEL',
  ANY_KEY: 'ANY_KEY',
};
